[package]
name = "fo_meta_server_map_viewer"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fo_meta_server = {path = "../..", features = ["map_viewer"]}
env_logger = "0.8"
